import Head from "next/head";
import FeatureComponentCopy from "../components/basic/FeatureComponentCopy";

export default function About() {
  return (
    <div>
      <Head>
        <title>Tanya - Corporate Journey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FeatureComponentCopy />
    </div>
  );
}