import Head from "next/head";
import Calendly from "../components/basic/calendly";

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Tanya - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Calendly />
    </div>
  );
}