import Head from "next/head";
import ProfessionComponents from "../components/basic/ProfessionComponents";

export default function Professional() {
  return (
    <div>
      <Head>
        <title>Tanya1 - Corporate Journey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfessionComponents />
    </div>
  );
}