import Head from "next/head";
import Services from "../components/basic/Services";

export default function Service() {
  return (
    <div>
      <Head>
        <title>Tanya - Corporate Journey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Services />
    </div>
  );
}